export const HTTP_CODES = {
  CLIENT: {
    BAD_REQUEST: 400,
    CONFLICT: 409,
    FORBIDDEN: 403,
    NOT_FOUND: 404,
    UNAUTHORIZED: 401,
    UNPROCESSABLE_ENTITY: 422,
  },
  SERVER: {
    INTERNAL: 500,
  },
  SUCCESS: {
    OK: 200,
  },
};
